version: 2
jobs:
    build:
      docker:
        - image: circleci/php:7

      steps:
        - checkout
        - run: bin/behat -V
        - run: echo "hello world"
        - run: pwd ; ls -l
        - run: ls -l vendor/
        - run: chmod -R 777 vendor/facebook/
        - run: ls -l vendor/
        - run: ls -l vendor/facebook
        - run: bin/behat -c config/single.conf.yml --tags '@database'

    database_scripts:
      docker:
        - image: circleci/php:7
      steps:
        - checkout
        - run: echo "hello world"
        - run: pwd ; ls
        - run: chmod -R 777 .
        - run: bin/behat -c config/single.conf.yml --tags '@database'

    test_scripts:
      docker:
        - image: circleci/php:7
      steps:
        - checkout
        - run:
            command: echo "bye world"

    completion:
      docker:
        - image: circleci/php:7
      steps:
        - run:
            name: Clean up old keys
            command: echo "All passed."

#workflows:
#  version: 2
#  build_test:
#    jobs:
#      - build
#      - database_scripts:
#          requires:
#            - build
#      - completion:
#          requires:
#            - database_scripts