version: 2
jobs:
    build:
      docker:
        - image: circleci/php:7

      steps:
        - checkout
        - run: bin/behat -V

    database_scripts:
      docker:
        - image: circleci/php:7
      steps:
        - checkout
        - run:
            command: echo "hello world"
            command: pwd ; ls
            command: chmod -R 777 .
            command: bin/behat -c config/single.conf.yml --tags '@database'

    test_scripts:
      docker:
        - image: circleci/php:7
      steps:
        - checkout
        - run:
            command: echo "bye world"

    completion:
      docker:
        - image: circleci/php:7
      steps:
        - run:
            name: Clean up old keys
            command: echo "All passed."

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - database_scripts:
          requires:
            - build
      - completion:
          requires:
            - database_scripts