version: 2
jobs:
    build:
      docker:
        - image: circleci/php:7

    code_deploy:
          docker:
            - image: circleci/php:7
          steps:
            - checkout
            - run:
                command: bin/behat -c config/single.conf.yml --tags '@code_deploy'

    database_scripts:
      docker:
        - image: circleci/php:7
      steps:
        - checkout
        - run: bin/behat -c config/single.conf.yml --tags '@database'

    integration_test_scripts:
      docker:
        - image: circleci/php:7
      steps:
        - checkout
        - run:
            command: bin/behat -c config/single.conf.yml --tags '@integration-test'
